### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Le0o0o** [stereolabs/zed-openni#1]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I did everything as it says, got to the part where it says "cmake .. -DOPENNI2_DIR='path-to-your-openni2-installation-folder' -DCMAKE_BUILD_TYPE=Release", where it says path i put my path to the openni.(i use linux) This is the terminal after i wrote that.. :
By not providing "FindZED.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ZED", but
  CMake did not find one.

  Could not find a package configuration file provided by "ZED" (requested
  version 3) with any of the following names:

    ZEDConfig.cmake
    zed-config.cmake

  Add the installation prefix of "ZED" to CMAKE_PREFIX_PATH or set "ZED_DIR"
  to a directory containing one of the above files.  If "ZED" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/pi/Desktop/OpenNI-Linux-Arm-2.2/zed-openni/build/CMakeFiles/CMakeOutput.log".

### Steps to Reproduce

1.Put verything as it says
2.Not working
3.
...

### Expected Result

It needed to work..

### Actual Result

Nothing

### ZED Camera model

ZED

### Environment

```shell
OS: LINUX
```

**Comment by Myzhar** [comment]
Hi @Le0o0o 
did you install the ZED SDK?
https://www.stereolabs.com/developers/release/

**Comment by Le0o0o** [comment]
yes i did...

**Comment by Myzhar** [comment]
Wait... In your log I read `/home/pi/`... are you using a Raspberry board?

**Comment by Le0o0o** [comment]
yes, is that a problem?

**Comment by Myzhar** [comment]
Yes, you do not have CUDA.
The ZED SDK requires CUDA to perform ZED camera processings.
